package com.back.capstone.service;
import com.back.capstone.dto.AuthDtos.*; import com.back.capstone.entity.User; import com.back.capstone.exception.ApiException; import com.back.capstone.repository.UserRepository; import com.back.capstone.security.JwtService; import java.nio.file.*; import java.util.UUID; import org.springframework.beans.factory.annotation.Value; import org.springframework.http.HttpStatus; import org.springframework.security.core.Authentication; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.web.multipart.MultipartFile;
@Service public class UserService { private final UserRepository users;private final PasswordEncoder encoder;private final JwtService jwt;private final Path root;
 public UserService(UserRepository u,PasswordEncoder e,JwtService j,@Value("${file.upload-dir}") String dir){users=u;encoder=e;jwt=j;root=Paths.get(dir).toAbsolutePath().normalize();}
 public AuthResponse register(RegisterRequest r){if(!r.password().equals(r.confirmPassword()))throw new ApiException(HttpStatus.BAD_REQUEST,"Passwords do not match.");if(users.existsByUsername(r.username()))throw new ApiException(HttpStatus.CONFLICT,"Username is already in use.");if(users.existsByEmail(r.email()))throw new ApiException(HttpStatus.CONFLICT,"Email is already registered.");User u=new User();u.setUsername(r.username().trim());u.setEmail(r.email().trim().toLowerCase());u.setPassword(encoder.encode(r.password()));users.save(u);return new AuthResponse(jwt.generate(u.getUsername()),safe(u));}
 public AuthResponse login(LoginRequest r){User u=users.findByUsernameOrEmail(r.usernameOrEmail(),r.usernameOrEmail()).orElseThrow(()->new ApiException(HttpStatus.UNAUTHORIZED,"Invalid username/email or password."));if(!encoder.matches(r.password(),u.getPassword()))throw new ApiException(HttpStatus.UNAUTHORIZED,"Invalid username/email or password.");return new AuthResponse(jwt.generate(u.getUsername()),safe(u));}
 public User current(Authentication a){return users.findByUsername(a.getName()).orElseThrow(()->new ApiException(HttpStatus.UNAUTHORIZED,"Authentication is no longer valid."));}
 public UserResponse me(Authentication a){return safe(current(a));} public UserResponse update(Authentication a,UpdateProfileRequest r){User u=current(a);String n=r.username().trim();if(!u.getUsername().equals(n)&&users.existsByUsername(n))throw new ApiException(HttpStatus.CONFLICT,"Username is already in use.");u.setUsername(n);users.save(u);return safe(u);}
 public void password(Authentication a,ChangePasswordRequest r){if(!r.newPassword().equals(r.confirmPassword()))throw new ApiException(HttpStatus.BAD_REQUEST,"New passwords do not match.");User u=current(a);if(!encoder.matches(r.currentPassword(),u.getPassword()))throw new ApiException(HttpStatus.BAD_REQUEST,"Current password is incorrect.");u.setPassword(encoder.encode(r.newPassword()));users.save(u);}
 public UserResponse image(Authentication a,MultipartFile file){if(file.isEmpty()||file.getContentType()==null||!file.getContentType().startsWith("image/"))throw new ApiException(HttpStatus.BAD_REQUEST,"Please upload a valid image.");try{Files.createDirectories(root.resolve("profiles"));String ext=extension(file.getOriginalFilename());String name=UUID.randomUUID()+ext;Files.copy(file.getInputStream(),root.resolve("profiles").resolve(name),StandardCopyOption.REPLACE_EXISTING);User u=current(a);u.setProfileImageStoredName(name);users.save(u);return safe(u);}catch(Exception e){throw new ApiException(HttpStatus.INTERNAL_SERVER_ERROR,"Could not store profile image.");}}
 public UserResponse safe(User u){String url=u.getProfileImageStoredName()==null?null:"/api/users/me/profile-image/content";return new UserResponse(u.getId(),u.getUsername(),u.getEmail(),url,u.getCreatedAt());} private String extension(String n){if(n==null)return "";int i=n.lastIndexOf('.');return i<0?"":n.substring(i).replaceAll("[^A-Za-z0-9.]","");}
 public Path profileImage(Authentication a){User u=current(a);if(u.getProfileImageStoredName()==null)throw new ApiException(HttpStatus.NOT_FOUND,"Profile image not found.");return root.resolve("profiles").resolve(u.getProfileImageStoredName()).normalize();}
}
